# Numpy Basic

In [1]:
import numpy as np

In [2]:
# Set seed for reproducebility
np.random.seed(seed=1234)

In [7]:
#Scalars
x = np.array(6)
print('x: ', x)
print('x ndim: ',x.ndim )
print('x shape: ', x.shape)
print('x size: ' ,x.size)
print('x dtype: ',x.dtype)

x:  6
x ndim:  0
x shape:  ()
x size:  1
x dtype:  int64


In [8]:
# 1-D Array
x2 = np.array([1.2,2.2,1.7])
print('x: ', x2)
print('x ndim: ',x2.ndim ) ## number of array dimensions
print('x shape: ', x2.shape) ## tuple of array dimensions.
print('x size: ' ,x2.size) 
print('x dtype: ',x2.dtype)

x:  [1.2 2.2 1.7]
x ndim:  1
x shape:  (3,)
x size:  3
x dtype:  float64


In [9]:
# 3-D array (matrix)
x = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print ("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
x ndim:  3
x shape: (1, 3, 3)
x size:  9
x dtype:  int64


In [14]:
demo = np.array((1,2,3))
print("demo: ",demo.shape)
demo2 = np.array([1,2,3])
print("demo2: ",demo2.shape)
demo3 = np.array(([1],[2]))
print("demo3: ",demo3.shape)

demo:  (3,)
demo2:  (3,)
demo3:  (2, 1)


In [15]:
#Functions:
print ("np.zeros((2,2)):\n", np.zeros((2,2)))
print ("np.ones((2,2)):\n", np.ones((2,2)))
print ("np.eye((2)):\n", np.eye((2)))
print ("np.random.random((2,2)):\n", np.random.random((2,2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


In [20]:
# Indexing
x = np.array([1,2,3])
print('x[0]',x[0])
x[0] = 0
print(x)

x[0] 1
[0 2 3]


In [23]:
# Some Basic Math of Matrix
x = np.array([[1,2],[3,4]],dtype = np.float64)
y = np.array([[1,2],[3,4]],dtype = np.float64)
print ("x + y:\n", np.add(x, y)) # or x + y
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y)) # or x * y

x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


In [25]:
# Dot Product
x = np.array([[1,2],[2,3]])
y = np.array([[1,3],[2,4]])
print(x.dot(y))

[[ 5 11]
 [ 8 18]]


In [33]:
# Sum across a dimention
x = np.array([[1,2],[4,3]])
print('sum: ', np.sum(x))
print('sum by col: ',np.sum(x,axis = 0))
print('sum by row: ',np.sum(x,axis = 1))

sum:  10
sum by col:  [5 5]
sum by row:  [3 7]


In [35]:
# Transposing
x = np.array([[1,2],[3,4]])
print('x\n',x)
print('x.t\n',x.T)

x
 [[1 2]
 [3 4]]
x.t
 [[1 3]
 [2 4]]


# Advanced

In [40]:
# Tile
x = np.array([[1,2],[3,4]])
y = np.array([5,6])
'''
np.tile(A ,repes)
A: array_like, The input array
reps: array_like The number of repetitions of A along each axis.

'''
addent = np.tile(y, (len(x) ,1 ))
print('addent: \n', addent)
z = x + addent
print ( 'z:\n ',  z)

addent: 
 [[5 6]
 [5 6]]
z:
  [[ 6  8]
 [ 8 10]]


In [41]:
# Some easier explanatioin on tile
a = np.array([0,1,2])
np.tile(a,2)

array([0, 1, 2, 0, 1, 2])

In [42]:
np.tile(a,(2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [43]:
np.tile(a,(2,2,2))

array([[[0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2]]])

In [51]:
# Reshaping
x = np.array([[1,2],[3,4],[5,6]])
print(x)
print('x.shape : ', x.shape)
y = np.reshape(x,(1,6))
print('y: ',y)
print('y.shape: ', y.shape)
# Must have same size

[[1 2]
 [3 4]
 [5 6]]
x.shape :  (3, 2)
y:  [[1 2 3 4 5 6]]
y.shape:  (1, 6)


In [62]:
# Removing dimensinos
x = np.array([[[1,2,1]],[[2,1,2]]])
print(x.shape)
y = np.squeeze(x,1) # delete dimension 1
print(y.shape)
print(y)

(2, 1, 3)
(2, 3)
[[1 2 1]
 [2 1 2]]
